### ISSUE TITLE
Build expanded data simulator 

### ISSUE THREAD

**Issue by kstoreyf** [panoptes/PIAA#11]
expand the fake data generator to generate a network of test data - make it include multiple units, specify multiple targets, input reasonable observing times. so that a realistic cloud-based pipeline can be tested

**Comment by kstoreyf** [comment]
draft created in #13

**Comment by kstoreyf** [comment]
next step is to input fake transit signals - guidance on what form these would take? slight decrease in flux over all colors (or just green?) over some extended period of time (hours - weeks)?

also, is there somewhere i can find more stars as test objects? i just found a few interesting ones from 2MASS

finally, what other functionality to make this simulator more useful/robust?

**Comment by wtgee** [comment]
Decrease in flux would be in all channels (they won't be the same in all channels but let's not worry about it for now) on the 1% level for 1-3 hours

What information do you want about more stars? Positions, stellar properties, etc?

**Comment by wtgee** [comment]
Take a look at the follow page which shows actual transit predictions. You can click on the name to get more info about the star but this page also lists the times, duration, star brightness, and depth of transit:

http://var2.astro.cz/ETD/predictions.php
