### ISSUE TITLE
Format and add metadata to JSON light curve

### ISSUE THREAD

**Issue by kstoreyf** [panoptes/PIAA#3]
figure out how to format light curve metadata and add it to the JSON light curve entry. could be cloning the FITS file header of the corresponding postage stamp cube

**Comment by kstoreyf** [comment]
also, figure out what other fields are needed in the JSON entry itself (ex: exposure duration for every timestamp?)

**Comment by joshwalawender** [comment]
Added metadata for the light curve to the relevant wiki page: https://github.com/panoptes/PIAA/wiki/Metadata-for-Images-and-Postage-Stamp-Cubes

please edit and expand the list as needed.

**Comment by wtgee** [comment]
I created #8 as a more generic metadata as this one feels more specific to the data generator. If not I can close the other.

**Comment by kstoreyf** [comment]
one way to add metadata to the json: create another field within the json object, like

```
{
    "metadata": {
        "SEQID": seqid,
        "FIELD": field,
        ...
    }
    "data": [
      {
        "time": "2016-07-17T21:10:47.612444",
        "exptime": 100.0,
        "R": 0.9969497512104571
        ...
      },
      {
        "time": "2016-07-17T21:02:06.136673",
        "exptime": 100.0,
        "R": 0.9988241698769387
        ...
      }
    ]
}
```
