### ISSUE TITLE
Choose format of master light curve

### ISSUE THREAD

**Issue by kstoreyf** [panoptes/PIAA#4]
decide on the format of the combined master light curve for each object - also JSON to start. need to include metadata about the object and the data cubes that went into it

**Comment by kstoreyf** [comment]
currently, master light curves are stored in a google cloud storage bucket, in a json file named by PIC.

next step is to choose more robust format, with the following considerations:

- append new light curves to the master as they are uploaded. currently, the entire master light curve for a star is rebuilt each time a new light curve segment for that star is added.
- should still have a way to rebuild master light curves from source light curve segments, or add all segments not already in the master, in case notification server is down and some were missed.
- need to figure out how to store metadata with master light curve about which light curve segments are included (another column(s) for each entry? repetitive but would work)

**Comment by wtgee** [comment]
@oguyon @joshwalawender @mimming I think this relates to both what is best t use on GCE as well as how we thinking the master lightcurves will be updated/used.
